### ISSUE TITLE
Operaciones con sistemas numericos

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Alondra-oss#1]
[operaciones con sistemas numericos++ (1).pdf](https://github.com/user-attachments/files/16842348/operaciones.con.sistemas.numericos%2B%2B.1.pdf)

**Comment by Victor-noe12** [comment]
Portada 25/25
Procedimiento 25/25
Figuras ilustrativas y fotografías 25/25
Resultados y Conclusiones 25/25
Calificación de la practica 20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
